apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxdemo
spec:
  replicas: 1000
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: nginx
        image: harbor.its.local/library/nginx-demo
---
kind: Service
apiVersion: v1
metadata:
  name:  nginxdemo
spec:
  selector:
    name:  nginxdemo
  type:  LoadBalancer
  ports:
  - name:  nginx
    port:  80
    targetPort:  80